# AUTOGENERATED! DO NOT EDIT! File to edit: ../Just_todo_process.ipynb.

# %% auto 0
__all__ = ['set_bands_name', 'set_bands_dir', 'set_single_band_name']

# %% ../Just_todo_process.ipynb 3
import os
import rasterio
def set_bands_name(file_path):
    '''
    The function renames the bands in the file
    '''
    dst_m= rasterio.open(file_path,'r+',  driver =  'GTiff')
    if dst_m.meta['count']==7:
        dst_m.set_band_description(1, "Optical_Depth_047")
        dst_m.set_band_description(2, "temperature_2m")
        dst_m.set_band_description(3, "PBLH")
        dst_m.set_band_description(4, "relative_humidity")
        dst_m.set_band_description(5, "total_precipitation")
        dst_m.set_band_description(6, "vialidades")
        dst_m.set_band_description(7, "PM25_predict")
    elif dst_m.meta['count']==6:
        dst_m.set_band_description(1, "Optical_Depth_047")
        dst_m.set_band_description(2, "temperature_2m")
        dst_m.set_band_description(3, "PBLH")
        dst_m.set_band_description(4, "relative_humidity")
        dst_m.set_band_description(5, "total_precipitation")
        dst_m.set_band_description(6, "vialidades")
    if dst_m.meta['count']==14:
        dst_m.set_band_description(1, "Optical_Depth_047")
        dst_m.set_band_description(2, "temperature_2m")
        dst_m.set_band_description(3, "PBLH")
        dst_m.set_band_description(4, "relative_humidity")
        dst_m.set_band_description(5, "total_precipitation")
        dst_m.set_band_description(6, "vialidades")
        dst_m.set_band_description(7, "PM25_predict")
        dst_m.set_band_description(8, "Optical_Depth_047_z")
        dst_m.set_band_description(9, "temperature_2m_z")
        dst_m.set_band_description(10, "PBLH_z")
        dst_m.set_band_description(11, "relative_humidity_z")
        dst_m.set_band_description(12, "total_precipitation_z")
        dst_m.set_band_description(13, "vialidades_z")
        dst_m.set_band_description(14, "PM25_predict_z")
    dst_m.close()
    return


def set_bands_dir(dir_path):
    ''' 
    The function changes the names of the bands inside the directory
    '''
    files_list = os.listdir(dir_path)
    files_list = [file  for file in files_list if ".tif" == file[-4:]]
    for file_na in files_list:
        print(dir_path+ file_na)
        set_bands_name(dir_path+ file_na )
    return


# %% ../Just_todo_process.ipynb 6
def set_single_band_name(file_path):
    '''
    The function renames the band in the file
    '''
    dst_m= rasterio.open(file_path,'r+',  driver =  'GTiff')

    dst_m.set_band_description(1, "Spline")
    dst_m.close()
    return
